version: '3'
services:
  web:
    networks:
      - default
      - ingress
    restart: always
    environment:
      VIRTUAL_HOST: graphql.wmflabs.org
networks:
  ingress:
    external:
      name: ingress
